name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: ctcpip/metrics@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: meaningless-metrics.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_ignored: forker, member, stargazer, gister, follower, automator, infographile
